# Generated by Django 5.1.2 on 2024-11-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="Students",
        ),
    ]
